language: python

python: '2.7'

notifications:
  email: false

sudo: enabled

dist: trusty

before_install:
- openssl aes-256-cbc -K $encrypted_5521cf2de878_key -iv $encrypted_5521cf2de878_iv
  -in secrets.py.enc -out src/secrets.py -d

install:
- pip install --target=src -r src/requirements.txt

script:
- python -m unittest discover -s tests -t tests -b

after_success:
- cd src
- zip -r alexa.zip *
- cd ..
- mkdir deploy-zip
- mv src/alexa.zip deploy-zip/

deploy:
  provider: lambda
  function_name: alexa-ChristChurchMayfairAssistant
  region: eu-west-1
  role: arn:aws:iam::882482748234:role/lambda_basic_execution
  runtime: python2.7
  module_name: alexa_main
  handler_name: lambda_handler
  zip: deploy-zip/alexa.zip
  timeout: 6
  access_key_id:
    secure: p/heXiQA5MLnim/lvlhn2ztlxZSGdmrgzDIb2M4K1G5dU8cmmt96l03AUR9jwSOgGPuk6KWOtaEuJFci/A7grV/kUyoHC4oHohm1eyXvVwfj7MehyJtj4DNAC4/tbdYG42NFCwEGRBJoaE9wEMmgOB16IzH03POOH013bz0Rn2uIVpJsch5OpP0p87NYHf5BVvLZRNVAyjAjlLKg6HhLaPnhIQFLRjNqq3qDuTPQxT9CP/XuJhUT0bVhycRuRPAXpqn3ap1OWI8vpCg80CkBT8jm525M1cVQHylYB0Z4BjcIGvtVJgBzkIQtXHXAu7c5FAmF4dvUGxcFO0nEcTg7iyfQ7/cS/RAxGl4R51j9VII8GrYRs9TPidwTlnMbY2wUNIy+5fIXCziExfK6xWmoAeTlScoYkzRNp+POVCqIEj7XsX+41DRFsWaihxQU2Ua9VzrGW+GqyPyisPk1lX+DJR7AmY7EYVnxWcTghmeE13bG1zaqN/8rWyI/qdR8ONjyomtQRpjoGhpLliWpwr9l4c+Hgp003cq5lT86IKCp9NdXg+nsbcp2XGLMW9VynBxHmDuO8q9lQDYBbf/hz8QRPcwm84Hsa3PAuJdlkCRZIRJbIblTAUWtpJjVHoWuGu52/K2GmQu1FXsuqt2TUGAqA4dMT+8uWbmFEW6CWjnEZGU=
  secret_access_key:
    secure: MJq4tyoKF0RO1QzcULZ6y2USjy5CgdwPH6ewRkd7p0jSuhCZoJ1vzC/DOQu9oKJ6Ql+diI7id4yReYTLTdB/Hh7Mk6ipTguqUF/y2lZKcwQV+xgTqNczHGhkrleV0oki3as7SV90Xd+fv+itvQ4XUTm2cUZ3cMuP+ucE08MBFWPjGgyPK30Wf8+pxNkC1GqGRY4hXKIqoYkaL6NbEYrX/ptCtrjVCpvdrdIGycHlZQCVaViWgUdxrsurwXjHJyb3WUFtkuwsIjcEc1dRf6FFgAkBfQO/xG1h18G61J+zdtbgSo1NvjEVGyyEOhBe31rvt+8wqsjKkr8nnK8Xh0FztDxSnHpMoDqu1PYSaRjrBJwIwE59IsS1jPNrzqUO4/DmFRDyQZVUgXl9iv0qZKg+18Wy4WajDl9weYb9wmqsh9dOxLrZ6eu1BeQw71oY5UvD9gEHTeeVr1gpsaYuckRNbTWTx9eXIrWPWZCaev+LKt6PBMMuSvHboWqS5mq2cbDtQ8FwU7jS/oe1lM1iv7d3ImU8zxY/2ILOUIsDMCx2sRJf7lYFmeQ+Hh4ateywnuUn0faanBNmGzaYmwIiCyi/zCQrneKiNC+KRqc5GW+Siiv3DSi9RAm7Cg0Wdg0/r9rz7QrjichdfjMTxaI/qXYAzBV9eWxya+3WfbsBT0qxDkM=
env:
  global:
    - PYTHONPATH=$TRAVIS_BUILD_DIR/src
    - secure: yG7hiwv1zZAn+n0SRURi+mMomKgJ/luWjk7dDZRqICMmUiCOf7FZwhcb0NY9/fOz6U4OUsHOMEgqtCqZtP4DsOcja+MTrlvwbVgSPzspJLNdoNwTFNbY4pKYayrwdhzhhVCOkVHMR4xqBHN6PaPdzXUQAZHMmauXM27ZRHAv0QwLf2tq+zcATQNABV4Enh31a0AloKq3uET0So5heOqzemKKNSFvToyNZRsoJnVoR6CNGCixZbY5DayXE/8ztOt5FEQ9qxaUaqjTG1XGtqwmsr5hnsltDEVi7kU3kjcFAJq9kt9Q//qWLrgS2vJoRa/sXkMS09zgadYJ8sNpO4ZohQ1fzcW35lxl3AD9Fp8WZjkK+eFxeGKavLlEG6av4XnZRiHk+2U8hU0kX/qQVP9v8KbuwXQ3pktDs3YiKUQdj7XRnnTzMzfqCNxv05aQjzw7Rc2ktvhxhVbdUrk/72wvMycZS7auT63mrbID/F35ym1SFJP1ZY6TV+/otFLcpgbC1iTk/vhQeJZWwR2uaPYhAb4zoKdXCbSDbElwWTtji9W0VQOSEzo8dt0PHjUl3Ki8n2rsZDb39DiF+oZ3RnRN9UCEkpNI4nW7zoNW0fcnfz/bmnOPTxhIAZGO1Mnbj97pd0PV6Iq04bpkV3DUfgNAbQ3AhhusasgYuKdmBUlGdro=

